// <auto-generated />
namespace Pilot.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FirstCrazySabbathDARP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstCrazySabbathDARP));
        
        string IMigrationMetadata.Id
        {
            get { return "201210140313476_FirstCrazySabbathDARP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
