// <auto-generated />
namespace Pilot.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ago02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ago02));
        
        string IMigrationMetadata.Id
        {
            get { return "201208281505304_ago02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
