// <auto-generated />
namespace Pilot.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Adding_Geom_Ruta_Usuario : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adding_Geom_Ruta_Usuario));
        
        string IMigrationMetadata.Id
        {
            get { return "201208300019571_Adding_Geom_Ruta_Usuario"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
