// <auto-generated />
namespace Pilot.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ScheduleRuta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ScheduleRuta));
        
        string IMigrationMetadata.Id
        {
            get { return "201210252121403_ScheduleRuta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
