// <auto-generated />
namespace Pilot.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddDistances : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDistances));
        
        string IMigrationMetadata.Id
        {
            get { return "201210231942416_AddDistances"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
