// <auto-generated />
namespace Pilot.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class horapartidaForce : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(horapartidaForce));
        
        string IMigrationMetadata.Id
        {
            get { return "201210211445436_horapartidaForce"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
