// <auto-generated />
namespace Pilot.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Ago01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ago01));
        
        string IMigrationMetadata.Id
        {
            get { return "201208241719556_Ago01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
