// <auto-generated />
namespace Pilot.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Calle_Interseccion_Geom : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Calle_Interseccion_Geom));
        
        string IMigrationMetadata.Id
        {
            get { return "201208290552162_Calle_Interseccion_Geom"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
