// <auto-generated />
namespace Pilot.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Calle_Interseccion_Way : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Calle_Interseccion_Way));
        
        string IMigrationMetadata.Id
        {
            get { return "201208290446500_Calle_Interseccion_Way"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
