// <auto-generated />
namespace Financy.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddBalance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBalance));
        
        string IMigrationMetadata.Id
        {
            get { return "201210012357526_AddBalance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
