// <auto-generated />
namespace Pilot.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MunicipioSolicitud : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MunicipioSolicitud));
        
        string IMigrationMetadata.Id
        {
            get { return "201210221731468_MunicipioSolicitud"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
