// <auto-generated />
namespace Financy.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class c20 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(c20));
        
        string IMigrationMetadata.Id
        {
            get { return "201210020127277_c20"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
