// <auto-generated />
namespace Financy.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TransaccionAdjust : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TransaccionAdjust));
        
        string IMigrationMetadata.Id
        {
            get { return "201210272242331_TransaccionAdjust"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
