// <auto-generated />
namespace Pilot.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SiSe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SiSe));
        
        string IMigrationMetadata.Id
        {
            get { return "201210180220016_SiSe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
