// <auto-generated />
namespace Financy.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddTipo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTipo));
        
        string IMigrationMetadata.Id
        {
            get { return "201210272043418_AddTipo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
