// <auto-generated />
namespace Pilot.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ForceFit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ForceFit));
        
        string IMigrationMetadata.Id
        {
            get { return "201210211917129_ForceFit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
